security:
    providers:
        our_db_users:
            entity:
                class: App:User
                property: uid

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            guard:
                authenticators:
                    - App\Security\FormLoginAuthenticator
            logout:
                path: security_logout

            switch_user: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
